### ISSUE TITLE
[Mod conflict] Library of Exile+Carpet+WorldEdit=crash

### ISSUE THREAD

**Issue by K0-RR** [RobertSkalko/Library-of-Exile#1]
Weird, I can run Carpet and WorldEdit mod without crash but when I add Library of Exile to mods then mc crashes.
Running Library of Exile with WorldEdit without Carpet doesn't crash.

crash report - https://hatebin.com/balwmiqfud

**Comment by K0-RR** [comment]
https://github.com/gnembon/fabric-carpet/issues/625

**Comment by RobertSkalko** [comment]
Pick one. I won't be updating for a while.

**Comment by K0-RR** [comment]
Carpet is more important to me
